services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    image: node:latest
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"

  frontend:
    image: node:latest
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    ports:
      - "8080:80"
    command: sh -c "npm install && npm run dev"

volumes:
  db-data:
